In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("original.csv")

In [4]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount
count        14.000000          15.000000   13.000000
mean       4103.571429        2509.333333  140.923077
std        2858.096481        3147.982090   86.032418
min        1299.000000           0.000000   17.000000
25%        2520.750000         350.000000  109.000000
50%        3118.000000        1526.000000  125.000000
75%        4858.250000        2672.000000  158.000000
max       12841.000000       10968.000000  349.000000

In [5]:
df.head()

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
0  LP001002     NaN           5849.0                0.0         NaN  urban   
1  LP001003    Male           4583.0                NaN       128.0   semi   
2  LP001005    Male           3000.0                0.0        66.0    NaN   
3  LP001006  Female           2583.0             2358.0       120.0   semi   
4  LP001008    Male              NaN                0.0       141.0  urban   

  Loan_Status  
0           Y  
1           N  
2           Y  
3         NaN  
4           Y

In [9]:
df.iloc[1:4,1:9]

Gender  ApplicantIncome  CoapplicantIncome  LoanAmount  Area Loan_Status
1    Male           4583.0                NaN       128.0  semi           N
2    Male           3000.0                0.0        66.0   NaN           Y
3  Female           2583.0             2358.0       120.0  semi         NaN

In [7]:
df[['Gender','ApplicantIncome','CoapplicantIncome']][1:4]

Gender  ApplicantIncome  CoapplicantIncome
1    Male           4583.0                NaN
2    Male           3000.0                0.0
3  Female           2583.0             2358.0

In [26]:
df.loc[1:4]

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
1  LP001003    Male           4583.0                NaN       128.0   semi   
2  LP001005    Male           3000.0                0.0        66.0   semi   
3  LP001006  Female           2583.0             2358.0       120.0   semi   
4  LP001008    Male              NaN                0.0       141.0  urban   

  Loan_Status  
1           N  
2           Y  
3           Y  
4           Y

In [11]:
df.shape

(16, 7)

In [12]:
df.columns

Index(['Loan_ID', 'Gender', 'ApplicantIncome', 'CoapplicantIncome',
       'LoanAmount', 'Area', 'Loan_Status'],
      dtype='object')

In [13]:
df.isnull().sum(axis=0)

Loan_ID              0
Gender               1
ApplicantIncome      2
CoapplicantIncome    1
LoanAmount           3
Area                 1
Loan_Status          1
dtype: int64

In [14]:
#Removing missing values
df.dropna()

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
5   LP001011    Male           5417.0             4196.0       267.0   semi   
7   LP001014  Female           3036.0             2504.0       158.0   semi   
8   LP001018    Male           4006.0             1526.0       168.0  rural   
9   LP001020    Male          12841.0            10968.0       349.0   semi   
10  LP001024  Female           3200.0              700.0        70.0  urban   
11  LP001027    Male           2500.0             1840.0       109.0  urban   
13  LP001029    Male           1853.0             2840.0       114.0  urban   
14  LP001030    Male           1299.0             1086.0        17.0   semi   
15  LP001032    Male           4950.0                0.0       125.0   semi   

   Loan_Status  
5            Y  
7            N  
8            Y  
9            N  
10           Y  
11           Y  
13           N  
14           Y  
15           Y

In [15]:
df.head()

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
0  LP001002     NaN           5849.0                0.0         NaN  urban   
1  LP001003    Male           4583.0                NaN       128.0   semi   
2  LP001005    Male           3000.0                0.0        66.0    NaN   
3  LP001006  Female           2583.0             2358.0       120.0   semi   
4  LP001008    Male              NaN                0.0       141.0  urban   

  Loan_Status  
0           Y  
1           N  
2           Y  
3         NaN  
4           Y

In [16]:
df.dropna(subset=['Loan_Status'])

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
0   LP001002     NaN           5849.0                0.0         NaN  urban   
1   LP001003    Male           4583.0                NaN       128.0   semi   
2   LP001005    Male           3000.0                0.0        66.0    NaN   
4   LP001008    Male              NaN                0.0       141.0  urban   
5   LP001011    Male           5417.0             4196.0       267.0   semi   
6   LP001013    Male           2333.0             1516.0         NaN  rural   
7   LP001014  Female           3036.0             2504.0       158.0   semi   
8   LP001018    Male           4006.0             1526.0       168.0  rural   
9   LP001020    Male          12841.0            10968.0       349.0   semi   
10  LP001024  Female           3200.0              700.0        70.0  urban   
11  LP001027    Male           2500.0             1840.0       109.0  urban   
12  LP001028  Female              NaN             8106.0         NaN  urban   
13  LP001029    Male           1853.0             2840.0       114.0  urban   
14  LP001030    Male           1299.0             1086.0        17.0   semi   
15  LP001032    Male           4950.0                0.0       125.0   semi   

   Loan_Status  
0            Y  
1            N  
2            Y  
4            Y  
5            Y  
6            Y  
7            N  
8            Y  
9            N  
10           Y  
11           Y  
12           Y  
13           N  
14           Y  
15           Y

In [18]:
df.columns

Index(['Loan_ID', 'Gender', 'ApplicantIncome', 'CoapplicantIncome',
       'LoanAmount', 'Area', 'Loan_Status'],
      dtype='object')

In [21]:
cols=['Gender','Area', 'Loan_Status']

In [23]:
df[cols]=df[cols].fillna(df.mode().iloc[0])

In [29]:
df.isnull().sum(axis=0)

Loan_ID              0
Gender               0
ApplicantIncome      2
CoapplicantIncome    1
LoanAmount           3
Area                 0
Loan_Status          0
dtype: int64

In [30]:
cols2=['ApplicantIncome','CoapplicantIncome','LoanAmount']

In [31]:
df[cols2]=df[cols2].fillna(df[cols2].mean())

In [32]:
df.isnull().sum()

Loan_ID              0
Gender               0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Area                 0
Loan_Status          0
dtype: int64

In [40]:
#Label Encoding
df.dtypes

Loan_ID                object
Gender               category
ApplicantIncome       float64
CoapplicantIncome     float64
LoanAmount            float64
Area                 category
Loan_Status          category
dtype: object

In [39]:
#Change datatype for objects
df[cols]=df[cols].astype('category')

In [42]:
for columns in cols:
    df[columns]=df[columns].cat.codes

In [43]:
df.head()

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount  Area  \
0  LP001002       1      5849.000000           0.000000  140.923077     2   
1  LP001003       1      4583.000000        2509.333333  128.000000     1   
2  LP001005       1      3000.000000           0.000000   66.000000     1   
3  LP001006       0      2583.000000        2358.000000  120.000000     1   
4  LP001008       1      4103.571429           0.000000  141.000000     2   

   Loan_Status  
0            1  
1            0  
2            1  
3            1  
4            1

In [45]:
#One hot encoding
df.drop(['Loan_ID'],axis=1)

Gender  ApplicantIncome  CoapplicantIncome  LoanAmount  Area  Loan_Status
0        1      5849.000000           0.000000  140.923077     2            1
1        1      4583.000000        2509.333333  128.000000     1            0
2        1      3000.000000           0.000000   66.000000     1            1
3        0      2583.000000        2358.000000  120.000000     1            1
4        1      4103.571429           0.000000  141.000000     2            1
5        1      5417.000000        4196.000000  267.000000     1            1
6        1      2333.000000        1516.000000  140.923077     0            1
7        0      3036.000000        2504.000000  158.000000     1            0
8        1      4006.000000        1526.000000  168.000000     0            1
9        1     12841.000000       10968.000000  349.000000     1            0
10       0      3200.000000         700.000000   70.000000     2            1
11       1      2500.000000        1840.000000  109.000000     2            1
12       0      4103.571429        8106.000000  140.923077     2            1
13       1      1853.000000        2840.000000  114.000000     2            0
14       1      1299.000000        1086.000000   17.000000     1            1
15       1      4950.000000           0.000000  125.000000     1            1

In [58]:
df1=pd.get_dummies(df,columns=['Area'],prefix='XXX')

In [60]:
df1.head()

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0  LP001002       1      5849.000000           0.000000  140.923077   
1  LP001003       1      4583.000000        2509.333333  128.000000   
2  LP001005       1      3000.000000           0.000000   66.000000   
3  LP001006       0      2583.000000        2358.000000  120.000000   
4  LP001008       1      4103.571429           0.000000  141.000000   

   Loan_Status  XXX_0  XXX_1  XXX_2  
0            1      0      0      1  
1            0      0      1      0  
2            1      0      1      0  
3            1      0      1      0  
4            1      0      0      1

In [72]:
df2=df1.iloc[:,2:5]
df2.head()

ApplicantIncome  CoapplicantIncome  LoanAmount
0      5849.000000           0.000000  140.923077
1      4583.000000        2509.333333  128.000000
2      3000.000000           0.000000   66.000000
3      2583.000000        2358.000000  120.000000
4      4103.571429           0.000000  141.000000

In [76]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [86]:
sc.fit_transform(df2)

array([[ 6.77506570e-01, -8.52161828e-01,  1.03911649e-16],
       [ 1.86095273e-01,  4.16333634e-17, -1.73449547e-01],
       [-4.28362928e-01, -8.52161828e-01, -1.00559440e+00],
       [-5.90225890e-01, -5.13923313e-02, -2.80823076e-01],
       [-5.55111512e-17, -8.52161828e-01,  1.03243778e-03],
       [ 5.09821198e-01,  5.72786776e-01,  1.69216552e+00],
       [-6.87266036e-01, -3.37332923e-01,  1.03911649e-16],
       [-4.14389147e-01, -1.81118348e-03,  2.29201187e-01],
       [-3.78733825e-02, -3.33936954e-01,  3.63418098e-01],
       [ 3.39152536e+00,  2.87253700e+00,  2.79274419e+00],
       [-3.50730811e-01, -6.14443996e-01, -9.51907631e-01],
       [-6.22443218e-01, -2.27303527e-01, -4.28461678e-01],
       [-5.55111512e-17,  1.90061067e+00,  1.03911649e-16],
       [-8.73583115e-01,  1.12293376e-01, -3.61353222e-01],
       [-1.08862408e+00, -4.83359592e-01, -1.66325726e+00],
       [ 3.28550207e-01, -8.52161828e-01, -2.13714620e-01]])

In [87]:
from sklearn.preprocessing import minmax_scale

In [88]:
minmax_scale(df2)

array([[0.39421244, 0.        , 0.37326228],
       [0.28452608, 0.22878677, 0.33433735],
       [0.14737481, 0.        , 0.14759036],
       [0.11124588, 0.21498906, 0.31024096],
       [0.24298834, 0.        , 0.37349398],
       [0.35678392, 0.38256747, 0.75301205],
       [0.08958586, 0.13822028, 0.37326228],
       [0.15049385, 0.22830051, 0.4246988 ],
       [0.23453474, 0.13913202, 0.45481928],
       [1.        , 1.        , 1.        ],
       [0.16470282, 0.06382203, 0.15963855],
       [0.10405476, 0.16776076, 0.27710843],
       [0.24298834, 0.73905908, 0.37326228],
       [0.04799861, 0.25893508, 0.29216867],
       [0.        , 0.09901532, 0.        ],
       [0.31632299, 0.        , 0.3253012 ]])

In [89]:
df1.head()

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0  LP001002       1      5849.000000           0.000000  140.923077   
1  LP001003       1      4583.000000        2509.333333  128.000000   
2  LP001005       1      3000.000000           0.000000   66.000000   
3  LP001006       0      2583.000000        2358.000000  120.000000   
4  LP001008       1      4103.571429           0.000000  141.000000   

   Loan_Status  XXX_0  XXX_1  XXX_2  
0            1      0      0      1  
1            0      0      1      0  
2            1      0      1      0  
3            1      0      1      0  
4            1      0      0      1

In [95]:
X=df1[['Loan_ID', 'Gender' ,'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'XXX_0', 'XXX_1', 'XXX_2']]
Y=df1.iloc[:,-5]

In [97]:
Y.head()

0    140.923077
1    128.000000
2     66.000000
3    120.000000
4    141.000000
Name: LoanAmount, dtype: float64

In [98]:
from sklearn.model_selection import train_test_split

In [100]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.25,random_state=1234)

In [102]:
x_test.head()

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount  XXX_0  \
13  LP001029       1      1853.000000             2840.0  114.000000      0   
11  LP001027       1      2500.000000             1840.0  109.000000      0   
0   LP001002       1      5849.000000                0.0  140.923077      0   
12  LP001028       0      4103.571429             8106.0  140.923077      0   

    XXX_1  XXX_2  
13      0      1  
11      0      1  
0       0      1  
12      0      1

In [103]:
### Kirill's course on data cleaning

In [104]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [107]:
pwd()

'C:\\Users\\Ayan Mukherjee\\Desktop'

In [143]:
df=pd.read_csv('Data.csv')

In [109]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [110]:
df.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [112]:
df.shape

(10, 4)

In [164]:
X=df1.iloc[:,:-1]
Y=df1.iloc[:,3]

In [116]:
Y.head()

0     No
1    Yes
2     No
3     No
4    Yes
Name: Purchased, dtype: object

In [121]:
df.isnull().sum(axis=0)

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [123]:
X=X.fillna(X.mean())

In [124]:
X

Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

In [126]:
Y.isnull().sum()

0

In [144]:
df.dtypes

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

In [145]:
cols3=['Country','Purchased']

In [146]:
df[cols3]=df[cols3].astype('category')

In [147]:
df.dropna()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [148]:
for columns in cols3:
    df[columns]=df[columns].cat.codes

In [155]:
df1=df.dropna()
df1

Country   Age   Salary  Purchased
0        0  44.0  72000.0          0
1        2  27.0  48000.0          1
2        1  30.0  54000.0          0
3        2  38.0  61000.0          0
5        0  35.0  58000.0          1
7        0  48.0  79000.0          1
8        1  50.0  83000.0          0
9        0  37.0  67000.0          1

In [156]:
df1=pd.get_dummies(df1,columns=['Country'])

In [157]:
df1

Age   Salary  Purchased  Country_0  Country_1  Country_2
0  44.0  72000.0          0          1          0          0
1  27.0  48000.0          1          0          0          1
2  30.0  54000.0          0          0          1          0
3  38.0  61000.0          0          0          0          1
5  35.0  58000.0          1          1          0          0
7  48.0  79000.0          1          1          0          0
8  50.0  83000.0          0          0          1          0
9  37.0  67000.0          1          1          0          0

In [158]:
from sklearn.model_selection import train_test_split

In [165]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.25,random_state=1234)

In [166]:
x_test

Age   Salary  Purchased  Country_0  Country_1
2  30.0  54000.0          0          0          1
1  27.0  48000.0          1          0          0

In [161]:
y_test

7    Yes
2     No
9    Yes
Name: Purchased, dtype: object

In [167]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [168]:
scaler.fit_transform(x_train)

array([[ 1.40690492,  1.44148148, -1.        , -1.41421356,  2.23606798],
       [ 0.35172623,  0.22176638, -1.        ,  0.70710678, -0.4472136 ],
       [-1.2310418 , -1.33059829,  1.        ,  0.70710678, -0.4472136 ],
       [ 1.05517869,  0.99794872,  1.        ,  0.70710678, -0.4472136 ],
       [-0.70345246, -0.99794872, -1.        , -1.41421356, -0.4472136 ],
       [-0.87931557, -0.33264957,  1.        ,  0.70710678, -0.4472136 ]])

In [169]:
scaler.fit_transform(x_test)

array([[ 1.,  1., -1.,  0.,  1.],
       [-1., -1.,  1.,  0., -1.]])